# application.yml

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    banner-mode: "off"
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,prometheus"

logging:
  level:
    root: INFO

global:
  prop1: "global-prop1 from application.yml"
  propOnlyInApp: "only-in-app from application.yml"
  
shared:
  defaultMsg: "default-shared from application.yml"
