spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  main:
    banner-mode: "off"
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,env,prometheus"

logging:
  level:
    root: INFO

# Ví dụ import "shared" (tùy bạn dùng hay không)
# spring.config.import:
#   - optional:configserver: # cho client khác; riêng ở đây chỉ là ví dụ
