# sample-service/application.yml - Base configuration
greeting:
  message: "Hello from ConfigRepo"
  delay-ms: 250
  timeout-ms: 5000
  enabled: true

feature:
  dark-mode: false
  new-endpoint-v2: false
  use-cache-v1: true

# Business configuration
business:
  max-retries: 3
  cache-ttl-seconds: 3600
  rate-limit-per-minute: 100

# Logging configuration
logging:
  level:
    com.example.sample: INFO

service:
  prop2: "service-default-prop2 from sample/application.yml"
  propOnlyInService: "only-in-service-default from sample/application.yml"

shared:
  defaultMsg: "shared-default-from-service from sample/application.yml"
